// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "firstrun": boolean;
      "namepattern": string;
      "namepatternCustom": string;
      "autoupdate": boolean;
      "ennamesplit": boolean;
      "zhnamesplit": boolean;
      "metadataSource": string;
      "pdfMatchFolder": string;
      "autoUpdateTranslators": boolean;
      "translatorSource": string;
      "cnkiAttachmentCookie": string;
      "translatorUpdateTime": string;
      "language": string;
    };
  }
}
