// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "firstRun": boolean;
      "enNameSplit": boolean;
      "zhNameSplit": boolean;
      "language": string;
      "autoUpdateMetadata": boolean;
      "namePattern": string;
      "namePatternCustom": string;
      "metadataSource": string;
      "isMainlandChina": boolean;
      "cnkiAttachmentCookie": string;
      "pdfMatchFolder": string;
      "autoUpdateTranslators": boolean;
      "translatorUpdateTime": number;
      "translatorSource": string;
      "enableBookmark": boolean;
    };
  }
}
